services:
  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_NAME: ${DATABASE_NAME}
    container_name: webhook-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - VITE_API_URL=${VITE_API_URL}
    # env_file:
    #   - .env
    ports:
      - "4001:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: webhook-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    # env_file:
    #   - .env
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true