name: Deploy Webhook-Receiver Application to GCP(Google Cloud Platform)

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GCP via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/webhook-repo
            git pull
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export DATABASE_NAME="${{ secrets.DATABASE_NAME }}"
            export VITE_API_URL="${{ secrets.VITE_API_URL }}"
            docker-compose up -d --build
